# Generated by Django 5.1 on 2024-08-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_username_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='user-profile.svg', null=True, upload_to='profile_images', verbose_name='Profile Pic'),
        ),
    ]
