# Generated by Django 5.1 on 2024-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_choice_question_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='wrong_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
