# Generated by Django 5.1 on 2024-09-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizsubmission_correct_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('quiz_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizsubmission')),
            ],
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='answers',
            field=models.ManyToManyField(through='quiz.SubmissionAnswer', to='quiz.question'),
        ),
    ]
