# Generated by Django 5.1 on 2024-11-21 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_choice_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_categories', to='quiz.quiz')),
            ],
            options={
                'verbose_name_plural': 'SubjectCategories',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.subjectcategory'),
            preserve_default=False,
        ),
    ]
