# Generated by Django 5.0.6 on 2024-08-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog_image_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(default='No summary available', max_length=255),
        ),
    ]
